# Generated by Django 2.0.5 on 2018-10-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='Odd_Length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desk',
            name='Odd_Width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desk',
            name='Area_Code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='desk',
            name='Hole_Quantity',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1),
        ),
        migrations.AlterField(
            model_name='desk',
            name='Length',
            field=models.IntegerField(choices=[(400, '400'), (450, '450'), (500, '500'), (600, '600'), (650, '650'), (700, '700'), (750, '750'), (800, '800'), (850, '850'), (900, '900'), (1100, '1100'), (1200, '1200'), (1350, '1350'), (1400, '1400'), (1450, '1450'), (1500, '1500'), (1600, '1600'), (1650, '1650'), (1700, '1700'), (1800, '1800'), (2100, '2100'), (-1, 'Other Measurements')], default=1500),
        ),
        migrations.AlterField(
            model_name='desk',
            name='Table_Shape',
            field=models.IntegerField(choices=[(0, 'L Shape Desk - Left Sided'), (1, 'L Shape Desk - Right Sided'), (2, 'Straight'), (3, 'P Shape'), (4, 'B Shape'), (5, 'Square'), (6, 'Oval'), (7, 'Boat Shape'), (8, 'Other'), (9, 'L Shape - Left OR Right')], default=3),
        ),
        migrations.AlterField(
            model_name='desk',
            name='Thickness_Details',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desk',
            name='Width',
            field=models.IntegerField(choices=[(400, '400'), (450, '450'), (500, '500'), (600, '600'), (650, '650'), (700, '700'), (750, '750'), (800, '800'), (850, '850'), (900, '900'), (1100, '1100'), (1200, '1200'), (1350, '1350'), (1400, '1400'), (1450, '1450'), (1500, '1500'), (1600, '1600'), (1650, '1650'), (1700, '1700'), (1800, '1800'), (2100, '2100'), (-1, 'Other Measurements')], default=600),
        ),
    ]
